# Site settings
title: Semyon Yurkov
tag_text: Marble Surf
description: This is a personal web page of Dr Semen Yurkov.
# baseurl: "/blog" # the subpath of your site, e.g. /blog
# url: "https://example.com" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
